# version: '3'
# services:
#   web:
#     build: .
#     command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
#     ports:
#       - "3000:3000"

version: '3'
services:
  # db:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #           POSTGRES_PASSWORD: postgres_password
  #   volumes:
  #     - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/watchlist
    ports:
      - "3000:3000"
    # depends_on:
    #   - db
    # environment:
    #   - PGPASSWORD=postgres_password